# Generated by Django 6.0 on 2025-12-31 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_photo_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
