# Generated by Django 6.0 on 2026-01-07 15:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_photo_tagged_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
