# Generated by Django 6.0 on 2026-01-07 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_album_is_public_album_share_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
