# Generated by Django 6.0 on 2026-01-07 17:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_album_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
