# Generated by Django 6.0 on 2026-01-07 18:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_alter_photo_share_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
