# Generated by Django 6.0 on 2025-12-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_otp',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
